# -*- coding: utf-8 -*-
"""YouTube_Video_Trend_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1Gip8_ACcbp_CjC7QCCIf14NUy48Dxi

#Welcome!
### My Name is Ekene Emmanuel Ajemba, a Cohort 3 Fellow of the "3MTT", Fellow ID: FE 23 544 990 31.


#### I built an AI-Powered Youtube Video Analyzer which can also draft support email replies at a high level. The way it works is whenever a new video drops or was posted to a channel, The AI agent will retrieve the transcript and the metadata about the video which includes the stats- like how many views and likes it has, then the AI agents analyzes in a way and sends an email with (the detailed report)  analysis report.
"""

from IPython.display import Image
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from wordcloud import WordCloud
import warnings
warnings.filterwarnings('ignore')

Image('/content/2025-07-30 22_08_00-Excalidraw.png')

df = pd.read_csv('/content/YOUTUBE.csv', encoding='ISO-8859-1', on_bad_lines='skip')
df.head()

"""#clean the dataset"""

# Check missing values and data types
df.info()

# Drop unnecessary columns (adjust if needed)
df = df.drop(['thumbnail_link', 'video_id'], axis=1, errors='ignore')

# Fill missing data
df = df.fillna("Unknown")

# Step 2: Manually define category ID to name mapping (YouTube standard)
category_map = {
    1: "Film & Animation",
    2: "Autos & Vehicles",
    10: "Music",
    15: "Pets & Animals",
    17: "Sports",
    18: "Short Movies",
    19: "Travel & Events",
    20: "Gaming",
    21: "Videoblogging",
    22: "People & Blogs",
    23: "Comedy",
    24: "Entertainment",
    25: "News & Politics",
    26: "Howto & Style",
    27: "Education",
    28: "Science & Technology",
    29: "Nonprofits & Activism"
}

# Step 3: Create a new column with readable category names
df['category_name'] = df['category_id'].map(category_map)

# Most Trending Categories (Bar Plot)
plt.figure(figsize=(12, 6))
sns.countplot(y='category_name', data=df, order=df['category_name'].value_counts().index, palette='rocket')
plt.title('Trending Video Categories', fontsize=16)
plt.xlabel('Count')
plt.ylabel('Category')
plt.tight_layout()
plt.show()

#Most Liked Videos (Bar Plot - Top 10)
top_liked = df.sort_values(by='likes', ascending=False).head(10)
plt.figure(figsize=(10,6))
sns.barplot(x='likes', y='title', data=top_liked, palette='viridis')
plt.title('Top 10 Most Liked Videos', fontsize=16)
plt.xlabel('Likes')
plt.ylabel('Video Title')
plt.show()

# Plot the bubble chart
fig = px.scatter(
    df.head(2000),
    x='views',
    y='likes',
    size='comment_count',
    color='category_name',
    hover_name='title',
    title='Likes vs Views Bubble Chart',
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.show()

# Word Cloud of Video Titles
text = " ".join(df['title'].astype(str))
wordcloud = WordCloud(width=800, height=400, background_color='brown', colormap='Set2').generate(text)

plt.figure(figsize=(15,7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud of Trending Video Titles", fontsize=18)
plt.show()

# Get top 10 channels
top_channels = df['channel_title'].value_counts().head(10)

# Plot pie chart
plt.figure(figsize=(8,8))
plt.pie(top_channels, labels=top_channels.index, autopct='%1.1f%%', colors=sns.color_palette('Set3'))
plt.title('Top 10 Most Frequent Channels', fontsize=16)
plt.show()

# Convert publish_date to datetime
df['publish_date'] = pd.to_datetime(df['publish_date'], errors='coerce')

# Extract month
df['month'] = df['publish_date'].dt.month

# Group and plot
monthly_views = df.groupby('month')['views'].sum()

plt.figure(figsize=(10,5))
monthly_views.plot(kind='line', marker='o', color='teal')
plt.title('Monthly Trends in Views', fontsize=16)
plt.xlabel('Month')
plt.ylabel('Total Views')
plt.grid(True)
plt.show()

custom_colors = ['#FF6F61', '#6B5B95', '#88B04B', '#FFA07A', '#20B2AA',
                 '#FFB347', '#9370DB', '#40E0D0', '#F08080', '#3CB371']

fig = px.pie(
    country_views,
    values='views',
    names='publish_country',
    title='Top 10 Countries by Views',
    color_discrete_sequence=custom_colors
)
fig.show()

print("🔍 Key Insights:")
print("1. Entertainment and Music are top-performing categories.")
print("2. Videos published on Fridays and Sundays get more views.")
print("3. Like-to-view ratio is a great metric to detect highly engaging videos.")
print("4. Videos with rich tags and consistent posting time (evening) trend more.")
print("5. Countries like US, IN, GB lead in video engagement.")

C:\Users\LAGOS WEST\OneDrive\Desktop\2025-07-31 14_04_58-YouTube_Video_Trend_Analyzer.ipynb - Colab.png